<%@include file="taglib_includes.jsp" %>
<%@include file="includes/header.jsp" %>

<div class="container_12">
        <script type="text/javascript">
            $(document).ready(function () {
                // $('input#familyName').gips({ 'theme': 'purple', autoHide: true, text: 'This is purple tooltip, auto hide after pausess time elapses.' });
                $('input#familyName').gips({ 'theme': 'green', placement: 'bottom', text: 'Please Enter Family Name.'  });
                $('input#givenName').gips({ 'theme': 'green', placement: 'bottom', text: 'Please Enter Given Name.'  });
                $('input#secondNameOrInitials').gips({ 'theme': 'green', placement: 'bottom', text: 'Second Name Or Initials.'  });
                $('input#fullName').gips({ 'theme': 'green', placement: 'bottom', text: 'Please Enter Full Name.'  });
                $('input#userName').gips({ 'theme': 'green', placement: 'bottom', text: 'Please Enter User Name.'  });
                $('textarea#description').gips({ 'theme': 'green', placement: 'bottom', text: 'Description.'  });
                $('input#targetCommunity').gips({ 'theme': 'green', placement: 'bottom', text: 'Target Home Community.'  });
                $('input#esMDClaimId').gips({ 'theme': 'green', placement: 'bottom', text: 'Claim Identifier is the identifier with which the provider submits the Claim to CMS. This could be found in the Additional Documentation Request (ADR) letter from Review Contractor.'  });
                $('input#esMDCaseId').gips({ 'theme': 'green', placement: 'bottom', text: 'Case Identifier is the identifier, generated by the Review Contractor to open a claim specific case. This could be found in Additional Documentation Request (ADR) letter from the Review Contractor if the request is from MACs.'  });
                $('input#intendedRecipient').gips({ 'theme': 'green', placement: 'bottom', text: 'Intended Recipient represents the organization(s) or person(s) for whom the Document Submission set is intended for In esMD, the Intended Recipient will be an organization (Review Contractor) to whom the sender (HIH) will submit the message with esMD Claim supporting Documents. This Intended Recipient will be identified by a HL7 issued organizational identifier (OID)'  });
                $('input#author').gips({ 'theme': 'green', placement: 'bottom', text: 'Represents the provider (NPI), who submits the Claim Supporting Documents in response to the Additional Documentation Request letter (ADR) from the CMS Review Contractor This attribute could either contain the following sub-attributes based on who (either Provider or institution NPI) submits the documentation:'  });
                $('input#authorInstitution').gips({ 'theme': 'green', placement: 'bottom', text: 'If there is only one document in the SubmissionSet, authorInstitution attribute of the SubmissionSet shall have the same NPI as the one used in the authorInstitution attribute at the document level. If there is more than one document in the SubmissionSet, authorInstitution attribute of the SubmissionSet shall have the NPI of the organization/institution which put together all the documents included in the SubmissionSet. Please note: At the SubmissionSet level, either the authorInstitution or authorPerson attribute shall be used but never both.'  });
                $('input#authorPerson').gips({ 'theme': 'green', placement: 'bottom', text: 'If there is only one document in the SubmissionSet, authorPerson attribute of the SubmissionSet shall have the same NPI as the one used in the authorPerson attribute at the document level. If there is more than one document in the SubmissionSet, authorPerson attribute of the SubmissionSet shall have the NPI of the provider who put together all the documents in the SubmissionSet. Please note: At the SubmissionSet level, either the authorInstitution or authorPerson attribute shall be used but never both.'  });
                $('input#contentTypeCode').gips({ 'theme': 'green', placement: 'bottom', text: 'The submission set is a response to Additional Documentation Request (ADR) from the Review Contractor. The ContentTypeCode is the code that specifies this – a Response to ADR'  });
                $('input#entryUUID').gips({ 'theme': 'green', placement: 'bottom', text: 'A unique ID or a globally unique identifier within the document submission request for the SubmissionSet. For example, “SubmissionSet01” can be entryUUID. It can also be in the UUID format. In the below example “SubmissionSet01” is used as entryUUID. This can also be UUID format.'  });
                $('input#submissionSet').gips({ 'theme': 'green', placement: 'bottom', text: 'Submission Set Status.' });
                $('input#sourceId').gips({ 'theme': 'green', placement: 'bottom', text: 'Globally unique identifier, in OID format, identifying the Health Information Handler (HIH) Gateway through which document/s were sent to the CMS esMD Gateway.'  });
                $('input#documentTitle').gips({ 'theme': 'green', placement: 'bottom', text: 'Represents the title of the document. Max length, 128 bytes, UTF-8.'  });
                $('input#PatientID').gips({ 'theme': 'green', placement: 'bottom', text: 'Since this is a required XDR field and we need to use it, we are going to populate this field with Claim ID. Since this field follows Root + Extension format, we are going to include CMS OID as the root and Claim ID as the extension, like so: CMS OID.ClaimID It is important to remember that Claim ID will also be populated in the attribute mentioned in row 1 of this table in addition to being populated here. Note: Soon, IHE might change PatientId to R2 ‘Required if known’.'  });
                $('input#creationTime').gips({ 'theme': 'green', placement: 'bottom', text: 'A unique ID or a globally unique identifier within the document submission request for the SubmissionSet. For example, “SubmissionSet01” can be entryUUID. It can also be in the UUID format. In the below example “SubmissionSet01” is used as entryUUID. This can also be UUID format.'  });
                $('input#serviceStartTime').gips({ 'theme': 'green', placement: 'bottom', text: 'Represents the start time of the provider service being documented.<br> This value will not be used by esMD (i.e., will be ignored). However, since this field is required by XDR, an input is required. Any possible value assigned by the sender will be accepted.<br> Not applicable to esMD but required by XDR Interoperability.'  });
                $('input#serviceStopTime').gips({ 'theme': 'green', placement: 'bottom', text: 'Represents the stop time of the provider service being documented. <br> This value will not be used by esMD (i.e., will be ignored). However, since this field is required by XDR, an input is required. Any possible value assigned by the sender will be accepted.'  });
                $('input#submissionTime').gips({ 'theme': 'green', placement: 'bottom', text: 'Point in Time when the SubmissionSet was created at the HIH CONNECT Adapter.'  });
                $('input#uniqueId').gips({ 'theme': 'green', placement: 'bottom', text: 'A globally unique identifier, in OID format, assigned by the HIH to the submission set in the transmission. The length of this Unique Identifier shall not exceed 128 bytes.'  });
                $('file#file').gips({ 'theme': 'green', placement: 'bottom', text: 'A unique ID or a globally unique identifier within the document submission request for the SubmissionSet. For example, “SubmissionSet01” can be entryUUID. It can also be in the UUID format. In the below example “SubmissionSet01” is used as entryUUID. This can also be UUID format.'  });
                $('input#confidentialityCode').gips({ 'theme': 'green', placement: 'bottom', text: 'Confidentiality Code.'  });
                $('input#classCode').gips({ 'theme': 'green', placement: 'bottom', text: 'Class Code.'  });
                $('input#formatCode').gips({ 'theme': 'green', placement: 'bottom', text: 'Format Code.'  });
                $('input#hcFacilityType').gips({ 'theme': 'green', placement: 'bottom', text: 'Healthcare Facility Type.'  });
                //$('input#yellow').gips({ 'theme': 'yellow', autoHide: true, placement: 'right' });
                // $('input#red').gips({ 'theme': 'red', placement: 'bottom' });
            });
        </script>
<form method="post" id="customForm" enctype="multipart/form-data" action="XDRRequestServlet">
                    <ul class="formMainUL" >
                        <li class="formHead"> <h2>User Info</h2></li>

                        <li class="leftFormLI">Family Name <span class="required">*</span></li>
                        <li class="rightFormLI"><input type="text" name="familyName" id="familyName" value="" /></li>


                        <li class="leftFormLI">Given Name <span class="required">*</span></li>
                        <li class="rightFormLI"><input type="text" name="givenName" id="givenName" value="" /></li>
                        <li><span id="givenNameInfo" class="error"></span></li>

                        <li class="leftFormLI">Second Name Or Initials</li>
                        <li class="rightFormLI"><input type="text" name="secondNameOrInitials" id="secondNameOrInitials" value="" /> <span id="secondNameOrInitialsInfo" class="error"></span></li>

                        <li class="leftFormLI">Full Name <span class="required">*</span></li>
                        <li class="rightFormLI"><input type="text" name="fullName" id="fullName" value="" /><span id="fullNameInfo" class="error"></span></li>

                        <li class="leftFormLI">User Name <span class="required">*</span></li>
                        <li class="rightFormLI"><input type="text" name="userName" id="userName" value="" /><span id="userNameInfo" class="error"></span></li>

                        <li class="leftFormLI" style="height:80px;">Description <span class="required">*</span></li>
                        <li class="rightFormLI" style="height:80px;"><textarea  name="description" id="description" rows="5" cols="25" ></textarea><span id="descriptionInfo" class="error"></span></li>

                        <li class="leftFormLI" style="height:80px;">Target Community <span class="required">*</span></li>
                        <li class="rightFormLI" style="height:80px;"><input type="text" name="targetCommunity" id="targetCommunity" value="" /><span id="targetCommunityInfo" class="error"></span></li>
                        
                    </ul>
                    <ul class="formMainUL" >

                        <li class="formHead"> <h2>Document Info</h2></li>

                        <li class="leftFormLI">ES MD Claim Id <span class="required">*</span></li>
                        <li class="rightFormLI"><input type="text" name="esMDClaimId" id="esMDClaimId" value="" /></li>

                        <li class="leftFormLI">ES MD Case Id <span class="required"></span></li>
                        <li class="rightFormLI"><input type="text" name="esMDCaseId" id="esMDCaseId" value="" /></li>

                        <li class="leftFormLI">Intended Recipient <span class="required">*</span></li>
                        <li class="rightFormLI"><input type="text" name="intendedRecipient" id="intendedRecipient" value="" /></li>

                        <li class="leftFormLI">Author <span class="required">*</span></li>
                        <li class="rightFormLI"><input type="text" name="author" id="author" value="" /></li>

                        <li class="leftFormLI">Author Institution <span class="required"></span></li>
                        <li class="rightFormLI"><input type="text" name="authorInstitution" id="authorInstitution" value="" /></li>

                        <li class="leftFormLI">Author Person <span class="required"></span></li>
                        <li class="rightFormLI"><input type="text" name="authorPerson" id="authorPerson" value="" /></li>

                        <li class="leftFormLI">Content Type Code <span class="required">*</span></li>
                        <li class="rightFormLI"><input type="text" name="contentTypeCode" id="contentTypeCode" value="" /></li>

                        <li class="leftFormLI">Entry UUID <span class="required">*</span></li>
                        <li class="rightFormLI"><input type="text" name="entryUUID" id="entryUUID" value="" /></li>

                        <li class="leftFormLI">Source Id <span class="required">*</span></li>
                        <li class="rightFormLI"><input type="text" name="sourceId" id="sourceId" value="" /></li>

                        <li class="leftFormLI">Document Title <span class="required"></span></li>
                        <li class="rightFormLI"><input type="text" name="documentTitle" id="documentTitle" value="" /></li>

                        <li class="leftFormLI">Patient id <span class="required">*</span></li>
                        <li class="rightFormLI"><input type="text" name="PatientID" id="PatientID" value="" /><span id="PatientIDInfo" class="error"></span></li>
                        
                    </ul>

                    <ul class="formMainUL" >

                        <li class="formHead"> <h2></h2></li>
                        <br/>

                        <li class="leftFormLI">Creation Time <span class="required">*</span></li>
                        <li class="rightFormLI"><input type="text" name="creationTime" id="creationTime" value="" /><span id="creationTimeInfo" class="error"></span></li>

                        <li class="leftFormLI">Service Start Time <span class="required">*</span></li>
                        <li class="rightFormLI"><input type="text" name="serviceStartTime" id="serviceStartTime" value="" /><span id="serviceStartTimeInfo" class="error"></span></li>

                        <li class="leftFormLI">Service Stop Time <span class="required">*</span></li>
                        <li class="rightFormLI"><input type="text" name="serviceStopTime" id="serviceStopTime" value="" /><span id="serviceStopTimeInfo" class="error"></span></li>

                        <li class="leftFormLI">Submission Time <span class="required">*</span></li>
                        <li class="rightFormLI"><input type="text" name="submissionTime" id="submissionTime" value="" /></li>

                        <li class="leftFormLI">Unique Id <span class="required">*</span></li>
                        <li class="rightFormLI"><input type="text" name="uniqueId" id="uniqueId" value="" /></li>

                        <li class="leftFormLI">Confidentiality Code<span class="required">*</span></li>
                        <li class="rightFormLI"><input type="text" name="confidentialityCode" id="confidentialityCode" value="" /></li>

                        <li class="leftFormLI">Class Code<span class="required">*</span></li>
                        <li class="rightFormLI"><input type="text" name="classCode" id="classCode" value="" /></li>

                        <li class="leftFormLI">Format Code<span class="required">*</span></li>
                        <li class="rightFormLI"><input type="text" name="formatCode" id="formatCode" value="" /></li>

                        <li class="leftFormLI">Healthcare Facility Type<span class="required">*</span></li>
                        <li class="rightFormLI"><input type="text" name="hcFacilityType" id="hcFacilityType" value="" /></li>

                        <li class="leftFormLI">Submission Set<span class="required">*</span></li>
                        <li class="rightFormLI"><input type="text" name="submissionSet" id="submissionSet" value="" /></li>

                        <li class="leftFormLI">Upload Document  <span class="required">*</span></li>
                        <li class="rightFormLI"><input type="file" name="file" id="file"/><span id="fileInfo" class="error"/></li>

                        <li class="leftFormLI"></li>
                        <li class="rightFormLI"><input type="submit" name="send" id="send" value="Submit" /></li>
                    </ul>
                </form>

</div>
<%@include file="includes/footer.jsp" %>
